### PR TITLE
Add terraform checking in circleCI

### PR DESCRIPTION
**Pull request by enicholson125**
This adds a bit of validation for the terraform.

### CODE REVIEW

**Review by eversC — COMMENTED** [review]
Thanks for this! Is it me or does the AWS fmt look a little odd?

**Comment by enicholson125** [comment]
> Thanks for this! Is it me or does the AWS fmt look a little odd?

It does, and I haven't been able to work out why. It's only doing it on circleCI - if I run terraform fmt locally I get what I'd expect (but then it fails in circleCI). Have you seen this behaviour before, by any chance? It feels like it can't be the terraform version because it's behaving as expected with the GCP one.

**Comment by enicholson125** [comment]
I worked out what was wrong with it - terraform fmt doesn't work well with EOF formatting. I've moved the majority of the code above the JSON blobs so that it isn't affected by that.

**Review by eversC — APPROVED** [review]
lgtm

**Pull request merged**
